version: "3"
services:
  ekas-data:
    image: omollo/ekas-data-portal-prod
    deploy:
      replicas: 3
      resources:
        limits:
          cpus: "0.8"
          memory: 3G
    ports:
      - "8083:8083"
      - "7001:7001"
    networks:
      - host
networks:
  host: