version: "3"
services:
  ekas-data:
    image: omollo/ekas-data-portal-prod
    container_name: ekas-data-portal
    deploy:
      replicas: 5
    ports:
      - "8083:8083"
      - "7001:7001"
    networks:
      - host
    volumes:
      - logs:/go/logs
volumes:
  logs:
networks:
  host: