version: "3"
services:
  ekas-data:
    image: omollo/ekas-data-portal-prod
    container_name: ekas-data-portal
    deploy:
      replicas: 5
    ports:
      - "8083:8083"
      - "7001:7001"
    networks:
      - host
    volumes:
      - logs:/go/logs
    depends_on:
      - "redis"

  redis:
    image: "redis:alpine"
    hostname: redis
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
        - ./storage/redis/data:/data
    restart: always
    environment:
      - REDIS_REPLICATION_MODE=master
volumes:
  logs:
networks:
  host: