version: "3"
services:
  ekas-data:
    image: omollo/ekas-data-portal-prod
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: "0.3"
          memory: 500M
    ports:
      - "8082:8082"
    networks:
      - host
networks:
  host: