version: "3"
services:
  ekas-data:
    image: omollo/ekas-data-portal-prod
    container_name: ekas-data-portal
    deploy:
      replicas: 3
      resources:
        limits:
          cpus: "0.5"
          memory: 2G
    ports:
      - "8083:8083"
      - "7001:7001"
    networks:
      - host
    volumes:
      - ekas_portal_data_container:/go/logs
volumes:
  ekas_portal_data_container:
networks:
  host: