version: "3"
services:
  ekas-data:
    image: omollo/ekas-data-portal-prod
    deploy:
      replicas: 4
      resources:
        limits:
          cpus: "0.3"
          memory: 500M
    ports:
      - "8083:8083"
    networks:
      - host
networks:
  host: